name = "cdemo"
main = "src/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

vars = { }

[[d1_databases]]
binding = "DB"
database_name = "bcdata"
database_id = "28338b0c-579f-44fd-915d-c70018e104d7"

[[kv_namespaces]]
binding = "CACHE"
id = "98731954c2f54fee873dece541deb406"
